// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/features/apple-pay': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/features/apple-pay.get').default>>>>
    }
    '/api/products/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
    }
    '/api/products/brand/:brand': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/brand/[brand].get').default>>>>
    }
    '/api/products/brands': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/brands.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/products/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/search.get').default>>>>
    }
    '/api/recommendations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recommendations.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recommendations.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}