// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/20/2025, 8:51:49 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/plugins/**/*.{js,ts,mjs}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/composables/**/*.{js,ts,mjs}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/utils/**/*.{js,ts,mjs}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/valerian.karsenty/Documents/App/val-commerce-demo-v2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;